/**
 * Class containing constants used in Authentication.
 */
export default class Constants {

  /**
   * Valid duration used for every access token generated by authentication.
   */
  public static defaultTokenDurationInMinutes = 5;
}
